version: '3.4'

services:
  alexbot:
    image: alexbot
    volumes:
      - ./:/alexbot
    build: .
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 bot.py"
      ]
    ports:
      - 5678:5678
  firefox:
    image: selenium/standalone-firefox
    shm_size: 2gb
